title: Danielle Pham
email: danielle.pham@mail.mcgill.ca
description: Canadian maker of crafts and code
url: "https://daniellepham.ca"
enforce_ssl: "daniellepham.ca"
github_username: quelledanielle

permalink: /thoughts/:title/
paginate_path: /thoughts/:num/
paginate: 10
timezone: America/Toronto

plugins: [jekyll-paginate]
