title: danielle pham
email: danielle.pham@mail.mcgill.ca
description: Canadian somebody
baseurl: "/"
url: "https://daniellepham.ca"
enforce_ssl: "daniellepham.ca"
github_username: quelledanielle

gems: [jekyll-paginate]

permalink: /thoughts/:title/
paginate_path: /thoughts/:num/
paginate: 10

markdown: kramdown
