title: x
email: danielle.pham@mail.mcgill.ca
description: Canadian somebody
baseurl: ""
url: "http://daniellepham.ca"
github_username: quelledanielle

permalink: /thoughts/:categories/:year/:month/:day/:title/
paginate_path: /thoughts/:num/
paginate: 10

markdown: kramdown
